apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: volume-data
          hostPath:
            path: /home/docker/data
      containers:
      - image: dutchcoders/transfer.sh
        resources:
        name: server
        ports:
        - containerPort: 8080
        args:
        - "-provider=local"
        - "-temp-path=/tmp/"
        - "-basedir=/data/"
        volumeMounts:
          - mountPath: "/data"
            name: volume-data